create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
create table order_statuses (order_status_id uuid not null, status varchar(255), primary key (order_status_id));
create table orders (created_date timestamp(6), last_modified_date timestamp(6), order_id uuid not null, order_status_order_status_id uuid, pizzas varchar(255) array, primary key (order_id));
alter table if exists orders add constraint FKonxtg4qet51il6ioosgj48e2u foreign key (order_status_order_status_id) references order_statuses;
