version: '3.8'
services:
  database:
    image: 'postgres:16.2'
    ports:
      - '15432:5432'
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_DB=pizzeria'
      - 'POSTGRES_PASSWORD=password'